# Generated by Django 4.2.5 on 2023-09-08 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rehber', '0006_alter_kisi_firma'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hareket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.FloatField(verbose_name='Miktar')),
                ('durum', models.CharField(choices=[('Alindi', 'Alindi'), ('Bekleniyor', 'Bekleniyor')], default=('Bekleniyor', 'Bekleniyor'), max_length=50, verbose_name='Durum')),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('hedef', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rehber.kisi')),
                ('yazar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
