# Generated by Django 4.2.5 on 2023-09-09 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hareket',
            name='tarih',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='hareket',
            name='durum',
            field=models.CharField(choices=[('Alindi', 'Alindi'), ('Alinacak', 'Alinacak')], default=('Alinacak', 'Alinacak'), max_length=50, verbose_name='Durum'),
        ),
    ]
