# Generated by Django 4.2.1 on 2023-09-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesap', '0002_hareket_tarih_alter_hareket_durum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.BooleanField(verbose_name='Emin misiniz?')),
            ],
        ),
    ]
