# Generated by Django 4.2.1 on 2023-09-13 14:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesap', '0003_sil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hareket',
            name='aciklama',
            field=ckeditor.fields.RichTextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hareket',
            name='tarih',
            field=models.DateField(blank=True, null=True, verbose_name='Tarih'),
        ),
    ]
