# Generated by Django 4.2.5 on 2023-09-13 20:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hesap', '0004_alter_hareket_aciklama_alter_hareket_tarih'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hareket',
            name='aciklama',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
