# Generated by Django 4.2.5 on 2023-09-16 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rehber', '0018_sil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hesap', '0005_alter_hareket_aciklama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hareket',
            name='hedef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rehber.kisi'),
        ),
        migrations.AlterField(
            model_name='hareket',
            name='yazar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
