# Generated by Django 4.2.5 on 2023-09-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kisi',
            name='tel1',
            field=models.CharField(default='1231231233', max_length=444),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kisi',
            name='tel2',
            field=models.CharField(default='1231231233', max_length=444),
            preserve_default=False,
        ),
    ]
