# Generated by Django 4.2.5 on 2023-09-08 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rehber', '0003_alter_kisi_adres_alter_kisi_notlar_alter_kisi_tel1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kisi',
            name='firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Firma', to='rehber.firma'),
        ),
        migrations.AlterField(
            model_name='kisi',
            name='grup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Grup', to='rehber.grup'),
        ),
    ]
