# Generated by Django 4.2.5 on 2023-09-08 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rehber', '0004_alter_kisi_firma_alter_kisi_grup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kisi',
            name='firma',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Firma', to='rehber.firma'),
        ),
    ]
