# Generated by Django 4.2.5 on 2023-09-09 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehber', '0006_alter_kisi_firma'),
    ]

    operations = [
        migrations.AddField(
            model_name='kisi',
            name='son_islem',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 9, 15, 43, 59, 218220)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kisi',
            name='total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
