# Generated by Django 4.2.5 on 2023-09-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehber', '0007_kisi_son_islem_kisi_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='kisi',
            name='son_miktar',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kisi',
            name='total',
            field=models.FloatField(),
        ),
    ]
