# Generated by Django 4.2.5 on 2023-09-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehber', '0009_alter_kisi_son_islem_alter_kisi_son_miktar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kisi',
            name='total',
            field=models.FloatField(blank=True),
        ),
    ]
