# Generated by Django 4.2.5 on 2023-09-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehber', '0010_alter_kisi_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kisi',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
