# Generated by Django 4.2.5 on 2023-09-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehber', '0011_alter_kisi_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kisi',
            name='son_miktar',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
