# Generated by Django 4.2.1 on 2023-09-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehber', '0014_remove_kisi_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kisi',
            name='son_islem',
            field=models.DateField(blank=True, null=True),
        ),
    ]
