# Generated by Django 4.2.5 on 2023-09-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehber', '0017_alter_kisi_adres_alter_kisi_notlar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.BooleanField(verbose_name='Emin misiniz?')),
            ],
        ),
    ]
