# Generated by Django 4.2.5 on 2023-09-16 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rehber', '0019_alter_firma_yazar_alter_kisi_firma_alter_kisi_yazar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kisi',
            name='firma',
        ),
        migrations.DeleteModel(
            name='Firma',
        ),
    ]
